# Language file you want to use
Language: EN
Log:
  #  
  # When enabled we will log entity removals into log files for future reference
  Enabled: true
  # Amount of entities need to be removed for log entry to be created
  # Helps out to void recording small amounts of regular cleanings
  From: 5
HopperControl:
  #  
  # Enables or disable hopper item transfer rate
  # Only for 1.8.x and above servers
  # By enabling this any contraptions based on regular hopper ticking will break and hopper transfer rate will be adjust dinamicaly
  # In case hopper is being used intensively, its transfer interval will get increased until max limit to lower load on server
  # It will get reseted if hopper is not used for particular time frame
  Enabled: true
  # Defines default item transfer rate in ticks (20 ticks 1 second). 8 is default vanilla behavior
  Default: 8
  # Defines max interval between item transfer. 40 will result in 1 item every 2 seconds.
  SlowestRate: 40
  # Defines how often to adjust hopper transfer rate in actual transfer. So 30 will mean that after hopper transfers 30 items, its rate will get adjusted
  AdjustEvery: 30
RedStone:
  #  
  # Enables redstone activity tracking which can then be checked in redstone command output
  # Only records last 60 seconds and only per chunk activity
  Track: true
WolfControl:
  #  
  # Checks tamed wolfs in defined chunk range and if its above allowed limit then makes them sit down
  # This is limit per player so value of 2-3 is more than enough
  Enabled: true
  # Defines max allowed wolfs per player which can follow him
  # This will be checked on general entity amount check defined belove
  Max: 8
EntitySpawn:
  #  
  # Checks Chunk when entity spawns
  Check: true
  # When set to true players without permissions: mfm.build.wither mfm.build.irongolem mfm.build.snowman will be prevented from building appropriate monsters
  PreventMobBuild: false
  # When set to true iron golems in villages will not spawn throw natural means
  PreventIronGolemSpawn: false
  # Range in chunks from origin. In example with range 2 all 9 (3x3) chunks will be counted as one and limits will be used as for one chunk
  # Values are limited to 1, 2 and 3, there is no need to have anything higher than this
  # At range of 3 chunks we will group 5x5 area which would amount to 25 chunks, use this option only if you want to have really strict limitations
  # In 99% of times 2 chunk range will do the trick
  GroupChunks: true
  GroupChunksRadius: 2
#  
# When set to true entities which are above allowed limit will get removed
# Disabling this will prevent entities from disappearing in front of your eyes, but this can allow player from stacking dozens or even hundreds of mobs in one chunk throw multiple methods
# Disable at your own risk
RemoveExisting: true
#  
# List of chunks we should exclude from entity checks
# Format - worldName:x:z
# For example - LtCraft:5:-1
ExcludedChunks: []
AutoClean:
  #  
  # Checks chunks around players for over populated farms
  Use: true
  #  
  # Informs users with mfm.cleaninform permission node how many entities we cleaned up and which ones in particular
  Inform: true
  # How often to check chunks in seconds. Minimal value: 15
  Interval: 60
  # Defines max amount of entities which we will remove from a chunk or chunk group when checking it
  # Set to 0 if you want to disable limit
  MaxRemoved: 0
  # When set to true and value for ChunkRadius is provided, we will group more then one chunk into check
  GroupChunks: true
  # Range around player in chunks to check. 2 means that 9 chunks will be checked, 3 - 25 chunks and so on
  # Max value is 5 to avoid unnecessary load on server
  # 1 = 1x1 area = 1 total chunks
  # 2 = 3x3 area = 9 total chunks
  # 3 = 5x5 area = 25 total chunks
  ChunkRadius: 2
  # Defines range from 1 to 2 in chunks we will check around player when performing autoclean
  # This only applies when you don't have GroupChunks enabled
  ExpandRange: 3
Commands:
  Clean:
    # Defines max amount of entities which we will remove from a chunk or chunk group when cleaning it
    # Set to 0 if you want to disable limit
    MaxRemoved: 0
    # If this set to true, chunks will be grouped up and counted as one. In example with range 2 all 9 (3x3) chunks will be counted as one and limits will be used as for one chunk
    # This will give wider range of mob cleaning
    # This only applies for clean command. If you want to keep similar or same behavior as other options, like auto clean or spawn listener, set this to the same values as those ones
    GroupChunks: false
    GroupChunksRadius: 1
Ignore:
  #  
  # When this set to true, armor stands with items on it will be ignored on chunk cleanup
  # Recomended to keep it at true to avoid player item deletion
  FullArmorStands: true
  #  
  # When this set to true, entities which picked items, will be ignored on chunk cleanup
  # Recommended to keep it at true to avoid player item deletion
  EntityWithPickedItem: true
  #  
  # When this set to true, item frames with items in it will be ignored on chunk cleanup
  # Recomended to keep it at true to avoid player item deletion
  FullItemFrames: true
  #  
  # When this set to true, tamed animals will be ignored
  # Recomended to keep it at true to avoid player animals being despawned
  TamedAnimals: true
  #  
  # When this set to true, animals with custom name will be ignored
  # Recomended to keep it at true to avoid special player animals being despawned
  NamedAnimals: true
  #  
  # When this set to true, animals with sadle will be ignored
  # Recomended to keep it at true to avoid special player animals being despawned
  WithSadle: true
  #  
  # When this set to true, baby animals will be ignored
  BabyAnimals: false
  #  
  # List of worlds to be ignored by plugin
  Worlds:
  - spawn
  - run
  - uwu
  - owo
  - sushi
  - contest
#  
# When enabled we will exclude disabled worlds from /mfm list command output
ExcludeDisabledFromList: false
BlockTypes:
  #  
  # Limitations to how many particular block we can place in each chunk
  # This can be bypassed with mfm.bypasslimit.[btype] permission node
  # New materials can be added manually if need be
  Limit: true
  # When enabled we will check piston moved blocks between chunks
  # This check can't be bypasses with mfm.bypasslimit.[btype] as we don't have player reference
  # Keep in mind that this can be more heavy on server side if you have more blocks set to be checked and players decide to abuse this check itself
  CheckPistonMove: false
  List:
    CRAFTER: 10
#  
# All possible spawn reassons to check
# Set to false if you don't want to do checks on particular spawn reasson
SpawnReasons:
  NATURAL: true
  JOCKEY: true
  CHUNK_GEN: true
  SPAWNER: true
  TRIAL_SPAWNER: true
  EGG: true
  SPAWNER_EGG: true
  LIGHTNING: false
  BUILD_SNOWMAN: true
  BUILD_IRONGOLEM: true
  BUILD_COPPERGOLEM: true
  BUILD_WITHER: true
  VILLAGE_DEFENSE: true
  VILLAGE_INVASION: true
  BREEDING: true
  SLIME_SPLIT: true
  REINFORCEMENTS: true
  NETHER_PORTAL: false
  DISPENSE_EGG: true
  INFECTION: true
  CURED: true
  OCELOT_BABY: true
  SILVERFISH_BLOCK: true
  MOUNT: false
  TRAP: true
  ENDER_PEARL: true
  SHOULDER_ENTITY: false
  DROWNED: true
  SHEARED: true
  EXPLOSION: true
  RAID: true
  PATROL: true
  BEEHIVE: true
  PIGLIN_ZOMBIFIED: true
  SPELL: true
  FROZEN: true
  METAMORPHOSIS: true
  DUPLICATION: true
  COMMAND: true
  ENCHANTMENT: true
  OMINOUS_ITEM_SPAWNER: true
  BUCKET: true
  POTION_EFFECT: true
  REANIMATE: true
  REHYDRATION: true
  CUSTOM: true
  DEFAULT: true
#  
# Settup for entity groups
# You can define different groups for different types of animals/monsters/entities
# If entity gets over total amount of group limit, he will not be allowed to spawn
EntityGroups:
  Animals:
    Use: true
    Limit: 35
    List:
    - Pig
    - Cow
    - Horse
    - Rabbit
    - Sheep
    - Chicken
    Worlds: []
  Monsters:
    Use: true
    Limit: 35
    List:
    - Zombie
    - Skeleton
    - Slime
    - Creeper
    - Squid
    - CREAKING
    Worlds: []
#  
# This list is automatically filled with ALL possible entities in game, so some of them can just not work until future update
EntityTypes:
  ACACIA_BOAT:
    Use: true
    # Max amount of entities, set to -1 if you want to disable limit
    # If you not sure what is that entity, then keep it at -1 limit, to not limit its spawning
    Limit: -1
    # When enabled entity will be included in automatic clean process
    # If not set then defaults to true
    AutoClean: true
    # When disabled entity will not be allowed to be spawn over natural means
    # Defaults to true if not set specifically
    NaturalSpawn: true
    # When enabled entity will be included in clean process while using /mfm clean command
    # If not set then defaults to true
    ManualClean: true
    # When enabled instead of removing entity entirely we will disable its AI lowering server resource usage without removing it
    # Keep in mind that this will bypass entity limit, but any entity over the limit will become inactive
    # If not set then defaults to false
    DisableAI: false
    # Defines limits by specific worlds
    # If world is not defined then default limit will be used
    # If world is provided then we will ignore default limit and will use provided for this specific world
    WorldLimit:
      spawn: -1
      builders: -1
      cave/bentobox: -1
      run: -1
      santa: -1
      acid: -1
      general: -1
      end: -1
      pixelasia: -1
      spawnupdate: -1
      nether: -1
      cave: -1
      oneblock: -1
      skygrid/bentobox: -1
      acid/bentobox: -1
      skyblock: -1
      skygrid: -1
      wild: -1
  ACACIA_CHEST_BOAT:
    Use: true
    Limit: -1
  ALLAY:
    Use: true
    Limit: 6
    AutoClean: true
    NaturalSpawn: true
    ManualClean: true
    DisableAI: true
    WorldLimit:
      spawn: -1
      builders: -1
      legacy: -1
      run: -1
      acid: -1
      general: -1
      end: -1
      pixelasia: -1
      nether: -1
      cave: -1
      vubbo: -1
      oneblock: -1
      skyblock: -1
      skygrid: -1
      wild: -1
  ARMADILLO:
    Use: true
    Limit: -1
  ARMOR_STAND:
    Use: true
    Limit: 50
  ARROW:
    Use: true
    Limit: -1
  AXOLOTL:
    Use: true
    Limit: 8
  BAMBOO_CHEST_RAFT:
    Use: true
    Limit: -1
  BAMBOO_RAFT:
    Use: true
    Limit: -1
  BAT:
    Use: true
    Limit: -1
  BEE:
    Use: true
    Limit: 18
  BIRCH_BOAT:
    Use: true
    Limit: -1
  BIRCH_CHEST_BOAT:
    Use: true
    Limit: -1
  BLAZE:
    Use: true
    Limit: 8
  BOGGED:
    Use: true
    Limit: -1
  BREEZE:
    Use: true
    Limit: -1
  BREEZE_WIND_CHARGE:
    Use: true
    Limit: -1
  CAMEL:
    Use: true
    Limit: 18
  CAMEL_HUSK:
    Use: true
    Limit: 18
  CAT:
    Use: true
    Limit: 12
  CAVE_SPIDER:
    Use: true
    Limit: 8
  CHERRY_BOAT:
    Use: true
    Limit: -1
  CHERRY_CHEST_BOAT:
    Use: true
    Limit: -1
  CHEST_MINECART:
    Use: true
    Limit: -1
  CHICKEN:
    Use: true
    Limit: 30
  COD:
    Use: true
    Limit: -1
  COMMAND_BLOCK_MINECART:
    Use: true
    Limit: -1
  COPPER_GOLEM:
    Use: true
    Limit: 12
    RemoveExisting: true
  COW:
    Use: true
    Limit: 40
  CREAKING:
    Use: true
    Limit: -1
  CREEPER:
    Use: true
    Limit: -1
  DARK_OAK_BOAT:
    Use: true
    Limit: -1
  DARK_OAK_CHEST_BOAT:
    Use: true
    Limit: -1
  DOLPHIN:
    Use: true
    Limit: 10
  DONKEY:
    Use: true
    Limit: -1
  DRAGON_FIREBALL:
    Use: true
    Limit: -1
  DROWNED:
    Use: true
    Limit: 12
  EGG:
    Use: true
    Limit: -1
  ELDER_GUARDIAN:
    Use: true
    Limit: 8
  ENDERMAN:
    Use: true
    Limit: 10
  ENDERMITE:
    Use: true
    Limit: -1
  ENDER_DRAGON:
    Use: true
    Limit: -1
  ENDER_PEARL:
    Use: true
    Limit: -1
  END_CRYSTAL:
    Use: true
    Limit: -1
  EVOKER:
    Use: true
    Limit: -1
  EXPERIENCE_BOTTLE:
    Use: true
    Limit: -1
  EXPERIENCE_ORB:
    Use: true
    Limit: -1
  EYE_OF_ENDER:
    Use: true
    Limit: -1
  FALLING_BLOCK:
    Use: true
    Limit: -1
  FIREBALL:
    Use: true
    Limit: -1
  FIREWORK_ROCKET:
    Use: true
    Limit: -1
  FISHING_BOBBER:
    Use: true
    Limit: -1
  FOX:
    Use: true
    Limit: 8
  FROG:
    Use: true
    Limit: 16
  FURNACE_MINECART:
    Use: true
    Limit: -1
  GHAST:
    Use: true
    Limit: -1
  GIANT:
    Use: true
    Limit: -1
  GLOW_ITEM_FRAME:
    Use: true
    Limit: -1
  GLOW_SQUID:
    Use: true
    Limit: -1
  GOAT:
    Use: true
    Limit: 8
  GUARDIAN:
    Use: false
    Limit: 32
  HAPPY_GHAST:
    Use: true
    Limit: 5
  HOGLIN:
    Use: true
    Limit: 5
  HOPPER_MINECART:
    Use: true
    Limit: -1
  HORSE:
    Use: true
    Limit: 45
  HUSK:
    Use: true
    Limit: 12
  ILLUSIONER:
    Use: true
    Limit: -1
  IRON_GOLEM:
    Use: true
    Limit: 8
  ITEM:
    Use: true
    Limit: -1
  ITEM_FRAME:
    Use: true
    Limit: -1
  JUNGLE_BOAT:
    Use: true
    Limit: -1
  JUNGLE_CHEST_BOAT:
    Use: true
    Limit: -1
  LIGHTNING_BOLT:
    Use: true
    Limit: -1
  LINGERING_POTION:
    Use: true
    Limit: -1
  LLAMA:
    Use: true
    Limit: -1
  MAGMA_CUBE:
    Use: true
    Limit: 10
  MANGROVE_BOAT:
    Use: true
    Limit: -1
  MANGROVE_CHEST_BOAT:
    Use: true
    Limit: -1
  MANNEQUIN:
    Use: true
    Limit: -1
  MARKER:
    Use: true
    Limit: -1
  MINECART:
    Use: true
    Limit: -1
  MOOSHROOM:
    Use: true
    Limit: 35
  MULE:
    Use: true
    Limit: -1
  NAUTILUS:
    Use: true
    Limit: -1
  OAK_BOAT:
    Use: true
    Limit: -1
  OAK_CHEST_BOAT:
    Use: true
    Limit: -1
  OCELOT:
    Use: true
    Limit: -1
  OMINOUS_ITEM_SPAWNER:
    Use: true
    Limit: -1
  PAINTING:
    Use: true
    Limit: -1
  PALE_OAK_BOAT:
    Use: true
    Limit: -1
  PALE_OAK_CHEST_BOAT:
    Use: true
    Limit: -1
  PANDA:
    Use: true
    Limit: 12
  PARCHED:
    Use: true
    Limit: -1
  PARROT:
    Use: true
    Limit: 10
  PHANTOM:
    Use: true
    Limit: 8
  PIG:
    Use: true
    Limit: -1
  PIGLIN:
    Use: true
    Limit: 35
  PIGLIN_BRUTE:
    Use: true
    Limit: -1
  PILLAGER:
    Use: true
    Limit: 32
  PLAYER:
    Use: true
    Limit: -1
  POLAR_BEAR:
    Use: true
    Limit: 10
  PUFFERFISH:
    Use: true
    Limit: -1
  RABBIT:
    Use: true
    Limit: 10
  RAVAGER:
    Use: true
    Limit: -1
  SALMON:
    Use: true
    Limit: -1
  SHEEP:
    Use: true
    Limit: 30
  SHULKER:
    Use: true
    Limit: 16
  SHULKER_BULLET:
    Use: true
    Limit: -1
  SILVERFISH:
    Use: true
    Limit: 4
  SKELETON:
    Use: true
    Limit: -1
  SKELETON_HORSE:
    Use: true
    Limit: 8
  SLIME:
    Use: true
    Limit: 12
  SMALL_FIREBALL:
    Use: true
    Limit: -1
  SNIFFER:
    Use: true
    Limit: -1
  SNOWBALL:
    Use: true
    Limit: -1
  SNOW_GOLEM:
    Use: true
    Limit: -1
  SPAWNER_MINECART:
    Use: true
    Limit: -1
  SPECTRAL_ARROW:
    Use: true
    Limit: -1
  SPIDER:
    Use: true
    Limit: -1
  SPLASH_POTION:
    Use: true
    Limit: -1
  SPRUCE_BOAT:
    Use: true
    Limit: -1
  SPRUCE_CHEST_BOAT:
    Use: true
    Limit: -1
  SQUID:
    Use: true
    Limit: -1
  STRAY:
    Use: true
    Limit: 12
  STRIDER:
    Use: true
    Limit: 5
  TADPOLE:
    Use: true
    Limit: -1
  TNT:
    Use: true
    Limit: -1
  TNT_MINECART:
    Use: true
    Limit: -1
  TRADER_LLAMA:
    Use: true
    Limit: -1
  TRIDENT:
    Use: true
    Limit: -1
  TROPICAL_FISH:
    Use: true
    Limit: -1
  TURTLE:
    Use: true
    Limit: 12
  VEX:
    Use: true
    Limit: 6
  VILLAGER:
    Use: true
    Limit: 20
    RemoveExisting: true
  VINDICATOR:
    Use: true
    Limit: -1
  WANDERING_TRADER:
    Use: true
    Limit: -1
  WARDEN:
    Use: true
    Limit: 6
  WIND_CHARGE:
    Use: true
    Limit: -1
  WITCH:
    Use: true
    Limit: -1
  WITHER:
    Use: true
    Limit: -1
  WITHER_SKELETON:
    Use: true
    Limit: 8
  WITHER_SKULL:
    Use: true
    Limit: -1
  WOLF:
    Use: true
    Limit: 20
  ZOGLIN:
    Use: true
    Limit: 5
  ZOMBIE:
    Use: true
    Limit: -1
  ZOMBIE_HORSE:
    Use: true
    Limit: 8
  ZOMBIE_NAUTILUS:
    Use: true
    Limit: -1
  ZOMBIE_VILLAGER:
    Use: true
    Limit: -1
  ZOMBIFIED_PIGLIN:
    Use: true
    Limit: 8
  POTION:
    Use: true
    Limit: -1
  CREAKING_TRANSIENT:
    Use: true
    Limit: -1
  BOAT:
    Use: true
    Limit: 50
  CHEST_BOAT:
    Use: true
    Limit: 25
  DROPPED_ITEM:
    Use: true
    Limit: -1
    AutoClean: true
    NaturalSpawn: true
    ManualClean: true
    WorldLimit:
      spawn: -1
  ENDER_CRYSTAL:
    Use: true
    Limit: -1
  FIREWORK:
    Use: true
    Limit: -1
  FISHING_HOOK:
    Use: true
    Limit: -1
  LIGHTNING:
    Use: true
    Limit: -1
  MINECART_CHEST:
    Use: true
    Limit: -1
  MINECART_COMMAND:
    Use: true
    Limit: -1
  MINECART_FURNACE:
    Use: true
    Limit: -1
  MINECART_HOPPER:
    Use: true
    Limit: -1
  MINECART_MOB_SPAWNER:
    Use: true
    Limit: -1
  MINECART_TNT:
    Use: true
    Limit: -1
  PRIMED_TNT:
    Use: true
    Limit: -1
  SNOWMAN:
    Use: true
    Limit: -1
  THROWN_EXP_BOTTLE:
    Use: true
    Limit: -1
  LEASH_HITCH:
    Use: true
    Limit: -1
  AREA_EFFECT_CLOUD:
    Use: true
    Limit: -1
  ENDER_SIGNAL:
    Use: true
    Limit: -1
  EVOKER_FANGS:
    Use: true
    Limit: -1
  LLAMA_SPIT:
    Use: true
    Limit: -1
  BLOCK_DISPLAY:
    Use: true
    Limit: -1
  INTERACTION:
    Use: true
    Limit: -1
  ITEM_DISPLAY:
    Use: true
    Limit: -1
  TEXT_DISPLAY:
    Use: true
    Limit: -1
  UNKNOWN:
    Use: true
    Limit: -1
