import { configMetadata, getEnvironmentVariables } from "./configMetadata.js";

const ENVIRONMENT_NAME = /^[A-Z][A-Z0-9_]*$/;
const PRIVATE_VALUE_PATTERNS = [
  /\b\d{17,20}\b/,
  /\/(?:Users|home)\//i,
  /[A-Za-z]:\\/,
  /\b(?:Bot|Bearer)\s+(?=[A-Za-z0-9._~-]{8,}\b)(?=[A-Za-z0-9._~-]*[0-9._~-])[A-Za-z0-9._~-]+/i,
  /\b(?:sk-[A-Za-z0-9_-]{8,}|AIza[A-Za-z0-9_-]{12,})\b/,
  /(?:^|[,\s])!?\.\.(?:\/|\\)/m,
];

function markdown(value) {
  return String(value ?? "")
    .replaceAll("|", "\\|")
    .replaceAll("\n", " ");
}

function validateRelativeValues(value, name) {
  for (const rawCandidate of String(value || "").split(",")) {
    const candidate = rawCandidate.trim().replace(/^!/, "");
    if (!candidate) {
      continue;
    }
    if (
      candidate.startsWith("/") ||
      /^[A-Za-z]:[\\/]/.test(candidate) ||
      candidate.includes("\\") ||
      candidate.split("/").includes("..")
    ) {
      throw new Error(`${name} contains an unsafe generated path.`);
    }
  }
}

export function validateConfigMetadata(metadata = configMetadata) {
  if (metadata.schemaVersion !== 1) {
    throw new Error("Unsupported configuration metadata schema version.");
  }

  const names = new Set();
  for (const section of metadata.environmentSections) {
    if (!section.title || !Array.isArray(section.variables) || !section.variables.length) {
      throw new Error("Every configuration metadata section must be named and non-empty.");
    }
    for (const entry of section.variables) {
      if (!ENVIRONMENT_NAME.test(entry.name) || names.has(entry.name)) {
        throw new Error("Configuration metadata contains an invalid or duplicate environment name.");
      }
      names.add(entry.name);
      if (!entry.description || !["public", "private", "secret"].includes(entry.sensitivity)) {
        throw new Error(`${entry.name} has incomplete documentation metadata.`);
      }
      if (entry.sensitivity !== "public" && (entry.defaultValue || entry.exampleValue)) {
        throw new Error(`${entry.name} must not contain a sensitive default or example.`);
      }
      if (["relative-path", "relative-glob-list"].includes(entry.type)) {
        validateRelativeValues(entry.defaultValue, entry.name);
        validateRelativeValues(entry.exampleValue, entry.name);
      }
    }
  }

  const pluginIds = new Set();
  for (const plugin of metadata.pluginProfiles) {
    if (!plugin.id || !plugin.label || pluginIds.has(plugin.id) || !plugin.profiles.length) {
      throw new Error("Plugin profile metadata contains invalid identity information.");
    }
    pluginIds.add(plugin.id);
    const profileIds = new Set();
    for (const profile of plugin.profiles) {
      if (!profile.id || profileIds.has(profile.id) || !["log", "yaml"].includes(profile.sourceType)) {
        throw new Error(`${plugin.label} contains invalid profile metadata.`);
      }
      profileIds.add(profile.id);
      if (!names.has(profile.includeVariable) || !names.has(profile.excludeVariable)) {
        throw new Error(`${plugin.label} profile metadata references an undocumented environment variable.`);
      }
      validateRelativeValues(profile.includeDefault, profile.includeVariable);
      validateRelativeValues(profile.excludeDefault, profile.excludeVariable);
    }
  }

  return true;
}

function assertGeneratedContentIsSafe(contents) {
  for (const [name, content] of Object.entries(contents)) {
    for (const pattern of PRIVATE_VALUE_PATTERNS) {
      if (pattern.test(content)) {
        throw new Error(`${name} failed the generated-content privacy check.`);
      }
    }
  }
}

export function renderEnvironmentExample(metadata = configMetadata) {
  const lines = [
    "# Generated by npm run docs:generate from src/configMetadata.js. Do not add live values here.",
    "# Create .env with: install -m 600 .env.example .env",
    "# Fill private identifiers and secrets only in the ignored, owner-only .env file.",
  ];

  for (const section of metadata.environmentSections) {
    const entries = section.variables.filter((entry) => entry.includeInExample);
    if (!entries.length) {
      continue;
    }
    lines.push("", `# ${section.title}.`);
    if (section.description) {
      lines.push(`# ${section.description}`);
    }
    for (const entry of entries) {
      lines.push(`# ${entry.description}${entry.condition ? ` ${entry.condition}` : ""}`);
      const value = entry.sensitivity === "public" ? entry.exampleValue : "";
      lines.push(`${entry.name}=${value}`);
    }
  }

  return `${lines.join("\n")}\n`;
}

export function renderEnvironmentDocumentation(metadata = configMetadata) {
  const lines = [
    "# Configuration reference",
    "",
    "Generated from `src/configMetadata.js`. Do not edit this file directly.",
    "",
    "The generator never reads `.env` or process environment values. Secret and private identifier fields remain blank in examples and do not receive schema defaults.",
  ];

  for (const section of metadata.environmentSections) {
    lines.push(
      "",
      `## ${section.title}`,
      "",
      ...(section.description ? [section.description, ""] : []),
      "| Variable | Type | Required | Exposure | Default | Description |",
      "| --- | --- | --- | --- | --- | --- |",
    );
    for (const entry of section.variables) {
      const defaultValue =
        entry.sensitivity === "public" && entry.defaultValue
          ? `\`${markdown(entry.defaultValue)}\``
          : "(blank)";
      const description = [entry.description, entry.condition, entry.deprecated ? "Deprecated." : ""]
        .filter(Boolean)
        .join(" ");
      lines.push(
        `| \`${entry.name}\` | ${entry.type} | ${entry.required ? "yes" : "no"} | ${entry.sensitivity} | ${defaultValue} | ${markdown(description)} |`,
      );
    }
  }

  return `${lines.join("\n")}\n`;
}

export function renderPluginProfileDocumentation(metadata = configMetadata) {
  const lines = [
    "# Plugin profile reference",
    "",
    "Generated from `src/configMetadata.js`. All paths are repository-relative globs; runtime validation rejects absolute paths and parent-directory traversal.",
  ];

  for (const plugin of metadata.pluginProfiles) {
    lines.push(
      "",
      `## ${plugin.label}${plugin.shared ? " (shared)" : ""}`,
      "",
      "| Profile | Source | Include variable | Default includes | Exclude variable | Default excludes |",
      "| --- | --- | --- | --- | --- | --- |",
    );
    for (const profile of plugin.profiles) {
      lines.push(
        `| \`${profile.id}\` | ${profile.sourceType} | \`${profile.includeVariable}\` | \`${markdown(profile.includeDefault)}\` | \`${profile.excludeVariable}\` | ${profile.excludeDefault ? `\`${markdown(profile.excludeDefault)}\`` : "(none)"} |`,
      );
    }
  }

  return `${lines.join("\n")}\n`;
}

function schemaProperty(entry) {
  const property = {
    type: "string",
    description: [entry.description, entry.condition].filter(Boolean).join(" "),
    "x-value-type": entry.type,
    "x-sensitivity": entry.sensitivity,
  };
  if (entry.type === "boolean") {
    property.enum = ["true", "false"];
  } else if (entry.type === "integer") {
    property.pattern = "^[0-9]+$";
  } else if (entry.type === "discord-id") {
    property.pattern = "^[0-9]{17,20}$";
  } else if (entry.type === "discord-id-list") {
    property.pattern = "^[0-9]{17,20}(,[0-9]{17,20})*$";
  }
  if (entry.sensitivity === "public" && entry.defaultValue) {
    property.default = entry.defaultValue;
  }
  if (entry.sensitivity !== "public") {
    property.writeOnly = true;
  }
  if (entry.deprecated) {
    property.deprecated = true;
  }
  return property;
}

export function renderEnvironmentSchema(metadata = configMetadata) {
  const variables = getEnvironmentVariables(metadata);
  const schema = {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    title: "LookupBot environment",
    description: "Security-aware schema generated from static configuration metadata.",
    type: "object",
    properties: Object.fromEntries(variables.map((entry) => [entry.name, schemaProperty(entry)])),
    required: variables.filter((entry) => entry.required).map((entry) => entry.name),
    additionalProperties: true,
    "x-plugin-profiles": metadata.pluginProfiles.map((plugin) => ({
      id: plugin.id,
      label: plugin.label,
      shared: Boolean(plugin.shared),
      profiles: plugin.profiles.map((profile) => ({
        id: profile.id,
        sourceType: profile.sourceType,
        includeVariable: profile.includeVariable,
        excludeVariable: profile.excludeVariable,
      })),
    })),
  };
  return `${JSON.stringify(schema, null, 2)}\n`;
}

export function renderConfigArtifacts(metadata = configMetadata) {
  validateConfigMetadata(metadata);
  const contents = {
    ".env.example": renderEnvironmentExample(metadata),
    "docs/generated/configuration.md": renderEnvironmentDocumentation(metadata),
    "docs/generated/plugin-profiles.md": renderPluginProfileDocumentation(metadata),
    "docs/generated/environment.schema.json": renderEnvironmentSchema(metadata),
  };
  assertGeneratedContentIsSafe(contents);
  return contents;
}
